# SAM configuration file for service-router service
version = 0.1

[default]
[default.global.parameters]
stack_name = "purrsurance-service-router"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
s3_prefix = "service-router"
parameter_overrides = "Environment=\"prod\" IntentionClassifierAgentId=\"VGAVD9PZO4\" IntentionClassifierAgentAliasId=\"KPKIPXSELH\" PolicyManagerAgentId=\"JL0CVDZIGF\" PolicyManagerAgentAliasId=\"XC7QJU3T9Y\" ChatHistoryTableName=\"agent-operator-prod-ChatHistory\" LogLevel=\"info\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
